//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Input/UniveralPlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UniveralPlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UniveralPlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UniveralPlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""PlayerClicking"",
            ""id"": ""3ae50ac2-4521-4057-aa4f-006fc48c3e4c"",
            ""actions"": [
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""01c42468-c092-4759-8f6f-c6c28ad79dac"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fdd5eb47-4925-46ff-8606-93db7063e2c3"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerClicking
        m_PlayerClicking = asset.FindActionMap("PlayerClicking", throwIfNotFound: true);
        m_PlayerClicking_Click = m_PlayerClicking.FindAction("Click", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerClicking
    private readonly InputActionMap m_PlayerClicking;
    private List<IPlayerClickingActions> m_PlayerClickingActionsCallbackInterfaces = new List<IPlayerClickingActions>();
    private readonly InputAction m_PlayerClicking_Click;
    public struct PlayerClickingActions
    {
        private @UniveralPlayerInputActions m_Wrapper;
        public PlayerClickingActions(@UniveralPlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Click => m_Wrapper.m_PlayerClicking_Click;
        public InputActionMap Get() { return m_Wrapper.m_PlayerClicking; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerClickingActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerClickingActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerClickingActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerClickingActionsCallbackInterfaces.Add(instance);
            @Click.started += instance.OnClick;
            @Click.performed += instance.OnClick;
            @Click.canceled += instance.OnClick;
        }

        private void UnregisterCallbacks(IPlayerClickingActions instance)
        {
            @Click.started -= instance.OnClick;
            @Click.performed -= instance.OnClick;
            @Click.canceled -= instance.OnClick;
        }

        public void RemoveCallbacks(IPlayerClickingActions instance)
        {
            if (m_Wrapper.m_PlayerClickingActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerClickingActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerClickingActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerClickingActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerClickingActions @PlayerClicking => new PlayerClickingActions(this);
    public interface IPlayerClickingActions
    {
        void OnClick(InputAction.CallbackContext context);
    }
}
